---
output:   
  md_document:
    variant: markdown_github
title: "Instructions"
---
# Instructions

## Data

* Upload a CSV file
* Choose `time` and `event` variables for survival analysis

## Analysis Tools

### Non-Parametric Methods

#### 1. Table

Providing a summary table of estimates of survival probability and cumulative hazard using either the **Kaplan-Meier** or **Fleming-Harrington** methods. Check the box `Show Confidence Interval?` to obtain two-sided 95\% confidence intervals (types: linear, log, log-log).

#### 2. Plot

Drawing survival and cumulative hazard curves for the data. Customize your plots by adding a risk table or a number of censored subjects barplot. You can draw stratified curves by selecting either a discrete variable or a continuous variable with specified cutpoints.

#### 3. Test

Providing results of a collection of weighted logrank tests for comparing survival distributions for two or more independent groups. For more information, see [`survMisc::comp`](https://www.rdocumentation.org/packages/survMisc/versions/0.5.5/topics/comp).

### Semi-Parametric Methods (Cox Proportional Hazard Model)

#### 1. Model Results

Providing a summary table of coefficient and hazard ratio estimates, standard errors, etc. Also calculating the log-likelihood and AIC of the model that can be used in model selection.

#### 2. Model Diagnosis

Graphically diagnosing the overall fit and proportional hazard (PH) assumptions of the cox proportional hazard model. 

### Parametric Methods

#### 1. Model Results

Calculating coefficients, acceleration factors and hazard ratios of exponential and weibull model. Also providing informations for model comparison.

#### 2. Model Diagnosis

Graphically diagnosing the distributional assumptions of the models. 

